### ISSUE TITLE
linuxmuster-turnkey

### ISSUE THREAD

**Issue by lemertens** [linuxmuster/linuxmuster-client-adsso#17]
The Wiki says in "[1] Installation" that a script "linuxmuster-cloop-turnkey" has to be executed, but this script does not exist in the deb-archive on https://archive.linuxmuster.net/bionic/ (though it does exit in the github source). 
You might want to adjust the wiki or add the turnkey script to the deb-File.

**Comment by jolly-jump** [comment]
Thanks @lemertens , 

there is a new debian package containing the script.
