### ISSUE TITLE
snaps don't work in domainuser homes

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-client-adsso#26]
If you want to use snap apps in Ubuntu (like Chromium and other) they don't work when you are logged in as a domain user. This is because snap expects the home to be in `/home/user` and not in a subdirectory (like `linuxmuster-adsso-setup` sets it up → `/home/cache/user`). More infos here: https://forum.snapcraft.io/t/how-can-i-use-snap-when-i-dont-use-home-user/3352

Is there a critical reason why all domain user homes are in `/home/cache/`? A workaround would be to change `override_homedir` to something like `/home/%d_%u` in `sssd.conf`.

**Comment by jolly-jump** [comment]
Hm, interesting. Well, not interesting, bullshit coding of the snap-developers as far as I followed the link.
Thanks for the input and the fix/workaround. 
I think we need to test this before merging - does it work for you?

**Comment by zefanja** [comment]
>  I think we need to test this before merging - does it work for you?

Yes, it does.

**Comment by jolly-jump** [comment]
Ok, we are still in an early phase, but a change like this needs to be brought to attention.
People are probably building scripts depending on /home/cache and the documentation needs to be fixed here: https://github.com/linuxmuster/linuxmuster-client-adsso/wiki maybe, I guess.
Anyway. I will add this for the next release.

**Comment by PLanB2008** [comment]
There are several problem with the current approach regarding snap packages. This is a deeper problem.

**Comment by foer** [comment]
Issue can be solved by:

`#sudo dpkg-reconfigure apparmor`

In the ncurse input box write down the path to the domainuser-homes:

`/home/cache/`

Thats's it. All snaps installed by the template user will be available for the domainusers.
